src/List/urls.py
from django.contrib import admin
from django.urls import path, include
#DataFlair
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Project.urls'))
]

src/Project/urls.py
from django.urls import path
from . import views
from List.settings import DEBUG, STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static
urlpatterns = [

    path('home/', views.Home, name="home"),
    path('', views.index, name='index'),
    path('items/', views.Food_Items, name='view'),
    path('upload/', views.upload, name='upload-Item'),
    path('update/<str:Item_id>', views.update_FoodItem),
    path('delete/<str:Item_id>', views.delete_FoodItem),

    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('photo/<str:pk>/', views.viewPhoto, name='photo'),
    path('contact/', views.Contact, name="contact"),

    path('dashboard/', views.dashboard, name="admin_dashboard"),
    path('adminCustomOrders/', views.adminCustomOrders, name="special_orders"),
    path('cusproducts/', views.createCustomOrders, name="create_CustomOrder"),
    path('update_adminCustomOrders/<str:pk>/',
         views.updateCustomOrders, name="update_CustomOrder"),
    path('delete_adminCustomOrders/<str:pk>/',
         views.deleteCustomOrders, name="delete_CustomOrder"),

    # Delivery



    path('choon/', views.choon, name='choon'),
    path('customerorder/', views.customerorder, name='customerorder'),
    path('shop/', views.shop, name='shop'),
    path('addroute/', views.addroute, name='addroute'),
    path('customerDetails/', views.customerDetails, name='customerDetails'),
    path('editroute/', views.editroute, name='editroute'),
    path('delete/', views.routeDelete, name='deleteroute'),
    path('rd/', views.rd, name='rd'),
    path('shopDetails/', views.shopDetails, name='shopDetails'),
    path('specialFood/', views.specialFood, name='specialFood'),
    path('calculation', views.calculation, name='calculation'),
    path('salary', views.salary, name='salary'),

    # cart
    path('cart/',views.cart,name="cart"),
    path('checkout/',views.checkout,name="checkout"),
    path('update_item/',views.updateItem,name="update_item"),
    path('login/',views.loginpage,name="login"),
    path('register/',views.register,name="register"),
    path('process_order/', views.processOrder, name="process_order"),

    # supplier
    # path('logout/', views.logoutUser, name="logout"),
    # path('user/', views.userPage, name="user-page"),
    # path('supdashb/', views.supdashb, name="supdashb"),
    # path('products/', views.products, name='products'),
    # path('supplier/<str:pk_test>/', views.supplier, name="supplier"),

    # path('create_order/', views.createOrder, name="create_order"),
    # path('update_order/<str:pk>/', views.updateOrder, name="update_order"),
    # path('delete_order/<str:pk>/', views.deleteOrder, name="delete_order"),
    # path('export-to-csv', views.export_to_csv, name="export-to-csv")



    # Employee
    path('addEmployee/', views.addEmployee, name="addEmployee"),
    path('viewEmployee/', views.viewEmployee, name="viewEmployee"),
    path('updateEmployee/<str:pk_test>/',
         views.updateEmployee, name="updateEmployee"),
    path('deleteEmployee/<str:pk_test>/',
         views.deleteEmployee, name="deleteEmployee"),
    path('salaryView/', views.salaryView, name="salaryView"),
    path('salaryUpdate/<str:pk_test>/',
         views.salaryUpdate, name="salaryUpdate"),
    path('adminControls/', views.adminControls, name="adminControls"),
    path('empSalaryView/', views.empSalaryView, name="empSalaryView"),



]
# DataFlair
if DEBUG:
    urlpatterns += static(STATIC_URL, document_root=STATIC_ROOT)
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

src/Project/models.py
from django.db import models
from django.contrib.auth.models import User
# DataFlair Models


class Category(models.Model):
    Name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.Name


class Item(models.Model):
    name = models.CharField(max_length=50)
    picture = models.ImageField(null=True, blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    discription = models.CharField(max_length=250, default="Available")
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name


@property
def imageURL(self):
    try:
        url = self.image.url
    except:
        url = ''
    return url

# special order


class Customorder(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Delivered', 'Delivered'),
    )

    DELIVERY = (
        ('Pick Up', 'Pick Up'),
        ('Home Delivery', 'Home Delivery'),
    )

    status = models.CharField(max_length=50, null=True, choices=STATUS)
    name = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=150, null=True)
    address = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=100, null=True)
    delivery = models.CharField(max_length=50, null=True, choices=DELIVERY)
    description = models.CharField(max_length=300, null=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


# supplier

class Supplier(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)



    def __str__(self):
        return self.name


class Product(models.Model):
    CATEGORY = (
        ('kilogram', 'kilogram'),
        (' liter', ' liter'),
    )

    name = models.CharField(max_length=200, null=True)
    price = models.FloatField(null=True)
    category = models.CharField(max_length=200, null=True, choices=CATEGORY)
    description = models.CharField(max_length=200, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Out for delivery', 'Out for delivery'),
        ('Delivered', 'Delivered'),
    )

    supplier = models.ForeignKey(
        Supplier, null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)
    quantity = models.FloatField(null=True)
    total_price = models.FloatField(null=True)

    def __str__(self):
        return self.product.name


# cart function

class Customer(models.Model):
    # onetoone customer can have one user,user can have one customer
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    # name as a string value
    name = models.CharField(max_length=200, null=True)
    # name as a string value
    email = models.CharField(max_length=200, null=True)
    password = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
        return self._imageURL


class Order(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):  # single order can have many order items
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class DeliveryAddress(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(
        Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address


# Delivery

# Create your models here.
class RouteDetails(models.Model):
    dname = models.CharField(max_length=200, null=True)
    rname = models.CharField(max_length=200, null=True)
    km = models.IntegerField(null=True)
    town = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.rname


class Customer_order(models.Model):
    orderName = models.CharField(max_length=200, null=True)
    orderDate = models.DateField(max_length=200, null=True)
    Quantity = models.IntegerField(null=True)

    def __str__(self):
        return self.orderName


class Shop_order(models.Model):
    shopname = models.CharField(max_length=200, null=True)
    fitem = models.CharField(max_length=200, null=True)
    qty = models.IntegerField(null=True)

    def __str__(self):
        return self.shopname

# Employee


class Employee(models.Model):
    JOBTITLE = (
        ('Manager', 'Manager'),
        ('Cashier', 'Cashier'),
        ('Cook', 'Cook'),
        ('Helper', 'Helper'),
        ('Rider', 'Rider'),
    )

    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    ename = models.CharField(max_length=255, null=True)
    email = models.EmailField(max_length=254, null=True)
    address = models.CharField(max_length=100, null=True)
    contactnumber = models.IntegerField(null=True)
    gender = models.CharField(null=True, max_length=50, choices=GENDER)
    jobtitle = models.CharField(null=True, max_length=100, choices=JOBTITLE)
    basicsalary = models.FloatField(null=True, default=0)
    othours = models.FloatField(null=True, default=0)
    otrate = models.FloatField(null=True, default=0)
    allowances = models.FloatField(null=True, default=0)
    netsalary = models.FloatField(null=True, default=0)

    def __str__(self):
        return self.ename

src/Project/forms.py
from django import forms
from .models import Item
from django.db.models import fields
from django.forms import ModelForm
from .models import Customorder

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# DataFlair


class ItemCreate(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

# special order

class CustomorderForm(ModelForm):
    class Meta:
        model = Customorder
        fields = ['name', 'email', 'address',
                  'phone', 'delivery', 'description']
        # widgets = {
        #     'delivery':forms.RadioSelect()
        # }

# Delivery
class RouteDetalisForm(forms.ModelForm):
    class Meta:
        model = RouteDetails
        fields = '__all__'

# Employee



class addEmployeeform(ModelForm):
    
    class Meta:
    
        model = Employee
        fields = {'id', 'ename', 'email', 'address', 'contactnumber', 'gender',
                  'jobtitle', 'basicsalary', 'othours', 'otrate', 'allowances', 'netsalary'}

src/Project/templates/FoodItem/Upload_form.html
{% extends 'FoodItem/main.html' %}
{% block content %}
{% load static %}
    
    
    
<form  class = "form" method = 'POST' enctype="multipart/form-data">
    <h4 class="display-3" style="color: black;font-size:50px;
    text-align:center;
    font-family:arial;
    ">Add New Food</h4>
    {% csrf_token %}
    <table class="table1" >
        <tbody>
        
        
        <tr>
            <th>Name</th>
            <td><input type="text" name="name" maxlength="55" pattern="[A-Za-z]+" required="Plese enter name" id="id_name"></td>
        </tr>

        <tr>
            <th>Picture</th>
            <td><input type="file" name="picture" accept="image/*" id="id_picture"></td>
        </tr>

        <tr>
            <th>Price</th>
            <td><input type="number" name="price" step="0.01" required="" id="id_price"></td>
        </tr>

        <tr>
            <th>Discription</th>
            <td><input type="text" name="discription" value="Available" maxlength="250" required="" id="id_discription"></td>
        </tr>

        <tr>
            <th>Category</th>
            <td><select name="category" required="" id="id_category">
            <option value="" selected="">---------</option>

            <option value="1">Cakes</option>

            <option value="2">Buns</option>

            <option value="3">Cutlet and Rolls</option>

            <option value="4">Sandwiches</option>

            <option value="5">Bread</option>

            <option value="6">Cookies</option>

            </select></td>
        </tr>
    
       
    </tbody>
    </table>
    <button type="submit" class="btn btn-danger">Submit</button> 
    <a href="{% url 'index' %}" class="btn btn-danger">Back</a>   
</form>

{% endblock %}

src/Project/templates/FoodItem/contact.html
{% extends 'FoodItem/main.html' %}
{% block content %}
{% load static %}


<div class="container">
       
    <div class="contact-box">
        <div class="contact-left">
           <span class="message">
                Send Us A Message
            </span>
            <form>
                
                <div class="input-row">
                    <div class="input-group">
                        <label>NAME</label>
                        <input type="text" placeholder="Isuru Chathuranga" id="name" onfocus="Name()"required>
                    </div>
                    
                    <div class="input-group">
                        <label>PHONE</label>
                        <input type="text" placeholder="+94 771 555555" required>
                    </div>
                
                
</div>
                <div class="input-row">
                    <div class="input-group">
                        <label>EMAIL</label>
                        <input type="email" placeholder="isuruchathuranga@gmail.com" required>
                    </div>
                    
                    <div class="input-group">
                        <label>SUBJECT</label>
                        <input type="text" placeholder="Demo" required>
                    </div>
                    
                    
</div>
                        
                <label>MESSAGE</label>                 
                <textarea rows="8" placeholder="Your Message"></textarea>
                
                <button type="submit" class = "buttons" required id="msg" onfocus ="Wrong">SEND</button>
            </form>
        </div>
        <div class="contact-right">
            
            <div class = "Information">
           
                
                <i class = "fas fa-envelope-open"></i> 
                <span class = "txt">EMAIL</span><br>
                <span class = "text" > banisbakers2021@itp.lk</span><br><br>
            </div>
            
            <div class = "Information">				
                <i class = "fas fa-phone"></i>
                <span class = "txt">PHONE</span><br>
                <span class = "text"> 011 7654321</span>                   
            </div>
            
            
            <div class = "Information">				
                <i class = "fas fa-map-marker-alt"></i>
                <span class = "txt">ADDRESS</span><br>
                <span  class = "text"> Banis bakery, No.1,Colombo 7, Colombo</span>
                <span class = "text">Sri Lanka  </span> <br><br>  
                          
            
            </div>
            
        </div>
    </div>
</div>



{% endblock %}

src/Project/templates/FoodItem/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/fontawesome.min.css">
</head>
<body>
<!-----------------navigation bar----------------->
<section id="nav-bar">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><img src="{% static 'images/logo2.png' %}"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Shop
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="#">Products</a></li>
                            <li><a class="dropdown-item" href="spec-order.html">Custom Order</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link login" href="{% url 'login' %}">Sign in</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</section>

<!-----------------top body part1----------------->
<section id="banner">
    <div class="container">
    <div class="row">
    <div class="col-md-6">
        <p class="promo-title">Welcome to <i>BANIS</i></p>
        <p>buy banis, buy banis, buy banis, buy banis, buy banis, buy banis, buy banis, buy banis, buy banis, buy banis, buy banis, </p>
    </div>
        <div class="col-md-6 text-center">
            <img src="{% static 'images/logo2.png' %}" class="img-fluid">
        </div>
    </div>
    </div>
    <img src="{% static 'images/wave3.png' %}" class="bottom-img">
</section>

<!-----------------body part 2 - 1st card set----------------->
<section id="sample-products">
    <div class="container text-center">
        <h1 class="title2">Our Products</h1>
        <div class="row text-center">
            <div class="row">
                <div class="col-md-4 sample-products">
                    <img src="{% static 'images/sbun2.1-1.png' %}" class="product-img">
                    <h4>Sausage Bun</h4>
                    <p>supiriyak tama ;););)</p>
                </div>
                <div class="col-md-4 sample-products">
                    <img src="{% static 'images/Cake12.1-1.png' %}" class="product-img">
                    <h4>Wedding Cake</h4>
                    <p>supiriyak tama ;)</p>
                </div>
                <div class="col-md-4 sample-products">
                    <img src="{% static 'images/burger1.1-1.png' %}" class="product-img">
                    <h4>Chicken Burger</h4>
                    <p>supiriyak tama ;);)</p>
                </div>
            </div>
        </div>
        <a href="{% url 'view' %}" button type="button" class="btn btn-primary">All Products</button></a>

    </div>
</section>

<!-----------------special orders----------------->
<section id="custom-orders">
    <div class="container">
        <h1 class="title3  text-center">do you need special order?</h1>
        <div class="row">
            <div class="col-md-6">
                <img src="{% static 'images/Cake4v3.png' %}" class="img-fluid2">
            </div>
            <div class="col-md-6">
                <p class="cus-title">If you have a design or idea whatever you want<br>click below and send us the details</p>
                <button type="button" class="btn btn-primary">Custom Order</button>
            </div>
        </div>
    </div>

</section>

<!-----------------customer reviews-----------------> <!--only if need this-->
<section id="cus-reviews">
    <div class="container">
        <h1 class="title4 text-center">Reviews</h1>
        <div class="row offset-1">
            <div class="col-md-5 cus-reviews">
                <p>la la la supiri,bla bla la la la supiri,bla bla  la la la supiri,bla bla  la la la supiri,bla bla
                    la la la supiri,bla bla  la la la supiri,bla bla .</p>
                <img src="{% static 'images/fe-cus1.1.png' %}">
                <p class="user-details"><b>Hinata Hyga</b><br>7th Hokage's Wife</p>
            </div>
            <div class="col-md-5 cus-reviews">
                <p>la la la supiri,bla bla la la la supiri,bla bla  la la la supiri,bla bla  la la la supiri,bla bla
                    la la la supiri,bla bla  la la la supiri,bla bla .</p>
                <img src="{% static 'images/ma-cus1.1.png' %}">
                <p class="user-details"><b>Monkey D.Luffy</b><br>King of the Pirates</p>
            </div>
            <!--<div class="col-md-5 cus-reviews">
                <p>la la la supiri,bla bla la la la supiri,bla bla  la la la supiri,bla bla  la la la supiri,bla bla
                    la la la supiri,bla bla  la la la supiri,bla bla .</p>
                <img src="images/customer/fe-cus2.1.png">
                <p class="user-details"><b>Wanda Maximoff</b><br>Scarlet Witch in Marvel.U</p>
            </div>-->
        </div>
    </div>
</section>

<!-----------------footer----------------->
<section id="footer">
    <img src="{% static 'images/wave4.png' %}" class="footer-img">
    <div class="container">
        <div class="row">
            <div class="col-md-4 footer-box">
                <img src="{% static 'images/logo2.png' %}">
                <p>Welcome to <i>BANIS</i><br>buy banis, buy banis, buy banis, buy banis, buy banis,
                    buy banis, buy banis, buy banis, buy banis, buy banis, buy banis, </p>

            </div>
            <div class="col-md-4 footer-box">
                <p><b>Contact us</b></p>
                <p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
                </svg> 011 7654321</p>
                <p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-map-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.598-.49L10.5.99 5.598.01a.5.5 0 0 0-.196 0l-5 1A.5.5 0 0 0 0 1.5v14a.5.5 0 0 0 .598.49l4.902-.98 4.902.98a.502.502 0 0 0 .196 0l5-1A.5.5 0 0 0 16 14.5V.5zM5 14.09V1.11l.5-.1.5.1v12.98l-.402-.08a.498.498 0 0 0-.196 0L5 14.09zm5 .8V1.91l.402.08a.5.5 0 0 0 .196 0L11 1.91v12.98l-.5.1-.5-.1z"/>
                </svg>Banis bakery, No.1,<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Colombo 7, Colombo </p>
                <p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                    <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z"/>
                </svg>banisbakers2021@itp.lk</p>
            </div>
            <div class="col-md-4 footer-box">
                <p><b>Shop</b></p>
                <p><a href="#">Products</a></p>
                <p><a href="spec-order.html">Special Orders</a></p>
            </div>
        </div>
        <hr>
        <p class="copyright">Website Done by IDK Gang</p>
    </div>
</section>

</body>
</html>

src/Project/templates/FoodItem/items.html
{% extends 'FoodItem/main.html' %}
{% load static %}
{% block content %}

    <h1 style="margin-left: 50%; margin-bottom: 50px;">OUR MENU </h1>

<br>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-header">
                    Categories
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <a href="{% url 'view' %}">All</a>
                    </li>
                    {% for category in category %}
                    <li class=" list-group-item">
                        <a href="{% url 'view' %}?category={{category.Name}}">
                            {{category.Name}}
                        </a>
                    </li>
                    {% endfor %}


                   
                  
                </ul>
            </div>

        </div>
        <div class="col-md-9">
            <div class="row">

                {% for items in items %}
                <div class="col-lg-4">
                  
                        <img class="thumbnail" src="{{items.picture.url}}" alt="Card image cap">

                        <div class="box-element product">
                            <h6><strong>{{items.name}}</strong></h6>

                    <hr>
                <button  class="btn btn-outline-secondary add-btn">Add to Cart</button>
				<a href="{% url 'photo' items.id %}" class="btn btn-outline-success">View</a>
				<h5 style="display: inline-block; float: right"><strong>Rs.{{items.price}}</strong></h5>
                    </div>
                </div>
               
                {% endfor %}


            </div>
    </div>
</div>
</div>
{% endblock %}

src/Project/templates/FoodItem/login.html
{% extends 'FoodItem/main.html' %}
{% load static %}
{% block content %}

	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>

							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>

								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>

				</div>
			</div>
		</div>
	</div>
	  {% endblock %}                                                         